### ISSUE TITLE
not binding initial model value

### ISSUE THREAD

**Issue by bruno-barros** [w11k/w11k-select#10]
I'm passing a model with some IDs, but the dropdown don't initialize these values. Always starts with no selected items.

<div w11k-select ng-model="item.role_ids">
´item.role_ids = [1,2,3];´

How could I acomplish that?

**Comment by pburgmer** [comment]
Hi @bruno-barros ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
