### ISSUE TITLE
Update to latest w11k-dropdownToggle

### ISSUE THREAD

**Issue by omri-shaiko** [w11k/w11k-select#14]
Hi
Can you please update in the bower dependency the version of w11k-dropdownToggle to the new one (0.2.0)?

Tnx!

**Comment by pburgmer** [comment]
Hi @omri-shaiko ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
