### ISSUE TITLE
The widget is not accessible using the keyboard

### ISSUE THREAD

**Issue by tallsam** [w11k/w11k-select#19]
When stepping through form elements the w11k widget is skipped.

**Comment by pburgmer** [comment]
Thanks for the feedback.
I will try to fix it in a future release.

**Comment by tallsam** [comment]
cool, thanks!

**Comment by pburgmer** [comment]
Hi @tallsam ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp

**Comment by pburgmer** [comment]
Hi @tallsam ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
