### ISSUE TITLE
Accept hash function as an argument

### ISSUE THREAD

**Issue by axelhzf-tuguu** [w11k/w11k-select#21]
I'm having problems with the hash function and complex models

```js
var options = [
{id: 1, comments: [1, 2, 3]},
{id: 2, comments: [4, 5, 6]}
];

var selected = {id : 1, comments: [3, 2, 1]}
```

The problems here is the order of the comments array. The hash function thinks they are different values. 

I think a good solution could be a new parameter to pass the hash function. In my case the hash function should compare only by id

**Comment by pburgmer** [comment]
I implemented it with the 'track by' syntax known from ngRepeat. Please see comment of #e7db96e to see some examples

**Comment by pburgmer** [comment]
Hi @axelhzf-tuguu ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
