### ISSUE TITLE
I would like to bind a function on the dropdown.onClose

### ISSUE THREAD

**Issue by joelchartier** [w11k/w11k-select#22]
It would be interesting to be able to pass a on-close fonction in the scope of the directive, which would be called inside scope.dropdown.onClose(), which is already implemented.

**Comment by pburgmer** [comment]
Implemented in 54ab150. Thanks for your pull request #23. I prefer a field in the already existing attribute w11kSelectConfig to keep the html clean. I hope that's fine for you.

**Comment by joelchartier** [comment]
This is perfect, thanks.

**Comment by pburgmer** [comment]
Hi @joelchartier ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp

**Comment by joelchartier** [comment]
Here you go my friend.

**Comment by pburgmer** [comment]
Thanks!
