### ISSUE TITLE
filtered list not reset after cleared with x-button

### ISSUE THREAD

**Issue by darkgod6** [w11k/w11k-select#25]
If you filter the list, and then clear the filter with the x-button, the filtered list is not reset and shows the same values as before the filter was cleared.
I only tested it on the demo page.

**Comment by kaihenzler** [comment]
@darkgod6 
thanks for reporting the issue. we fixed it in 0.7.1

update for the demo page is coming soon

**Comment by pburgmer** [comment]
Hi @darkgod6,

If you're still using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
