### ISSUE TITLE
Unable to set ngModel with require-validation

### ISSUE THREAD

**Issue by kesdeband** [w11k/w11k-select#27]
Cannot set a default value for dropdown select if require-validation is enabled and the required attribute is place on the form element

**Comment by pburgmer** [comment]
Hi,

required via attribute is not supported. Only via w11k-select-options. Please look at the readme for an example how to use it. Do you need the attribute-way? Or can you use our options-object?

**Comment by kesdeband** [comment]
I am sorry but the required config variable does not activate the required validation as intended. I am using angular 1.2.30 and for it to work I had to set the name and required attributes.

I must admit that I did change the directive definition a bit see below:

    controller.$validators.required = validateRequired; // removed
    controller.$setValidity('required', validateRequired); // added

I commented out the validation setter for the old syntax as needed since i was getting an error based on my angular version.

Besides this change everything remains and works fine. The only exception is that I cannot set a default value on the w11k-select. Removing the required attribute solves this problem, however, I am unable to show validation messages if the field is left empty.

So my general question is how to get access to the validation error state(s) if the w11k-select is place within a form?

**Comment by pburgmer** [comment]
Angular 1.2 is not supported anymore. Please the the changelog.

`controller.$setValidity('required', validateRequired)` will not work. In Angular 1.2 you have to register a parser function and call $setValidity within it with `controller.$setValidity('required', true || false)`. See https://github.com/w11k/w11k-select/commit/797aff0230c8c7ded0bb39514101e19826dac066

Maybe I have some time next week to release a version supporting 1.2 as well.

**Comment by pburgmer** [comment]
Lighter than thought. I release 0.7.3 which adds support for AngularJS 1.2 again. Required validation should work as expected.

**Comment by kesdeband** [comment]
This still does not solve the problem, let me explain again.

I am using the w11k-select as a form element. Form validation requires that the elements have a name attribute in order to capture specific validation errors to display to the user in real time.

Base on the above how do I capture the required validation error of the w11k-select using the angular methodology?

When I inspect the ngModel/controller of an instance of the directive it shows the name value as undefined. Also the property $invalid is set to false even if the model value is empty.

Based on observation, settings the required config variable simple ensures that once a value is selected it cannot be cleared and thus the user can only change a value. What if the validation must happen if the user initially does not select a value?

Hope I am clearer now on those two points of interest.

**Comment by pburgmer** [comment]
Form validation and integration should work. Please see http://w11k.github.io/w11k-select/ and the corresponding code at https://github.com/w11k/w11k-select-page/tree/master/src.
If this does not solve your problem, provide a plunker/jsbin with example code.
