### ISSUE TITLE
This package doesn't work with requireJS.

### ISSUE THREAD

**Issue by vladislavBoshnakov** [w11k/w11k-select#31]
Hi I'm using requireJS to load my dependencies.  I had to ruffle through the code to find out the exact module names but even when I include w11k.dropdownToggle and w11k.select.template it still doesn't work. Can you supply a guide or modify the code ?

**Comment by pburgmer** [comment]
Hi,

Sorry for delay.

We will rewrite the code soon to support all kinds of module systems. We will distribute a UMD file and the export will be the Angular-Module. You will be able to include this module as a dependency of your own Module via module.name.

**Comment by CanKattwinkel** [comment]
@vladislavBoshnakov we've just released a new version including support for multiple module loader. Please reach out if the issue persists with version 0.10.2
