### ISSUE TITLE
Unknown provider gulp

### ISSUE THREAD

**Issue by kesdeband** [w11k/w11k-select#32]
There seems to be a minification mishaps when using gulp-uglify. Unknown provider error is thrown by angular.

**Comment by pburgmer** [comment]
Hi,

Sorry for delay.

Two questions: 
* Do you install the package via npm or bower?
* Do you use ng-annotate in your gulp setup?

If you use npm, you will consume the source code (build version if you use bower). Within our code we use ng-annotate to mark functions that will receive injected parameters. We do not use one of the explicit notations (array-notation or $inject).

Best regards,
Philipp

**Comment by kesdeband** [comment]
I installed the package using bower to answer your first question.

Secondly, yes I am using ng-annotate in the gulp setup (**why does this matter?**)

I am doing an optimization step for all my libraries (js files) where they are bundled and minified together but this is the only library which is broken after the process.

**Comment by pburgmer** [comment]
Hi,

Using ng-annotate does only matter if you use npm to install. As I said, you will get the source code instead of a build version right now. We are working on that.

But since you use this bower this seems to be a bug. Which provider is missing?

@CanKattwinkel please fix it and release a new pre-typescript-version

**Comment by kesdeband** [comment]
I wont be able to tell which provider because as I mentioned it is after my bundling and minification process using gulp. The library works before this final build process. I am using gulp-uglify by the way.

So I assume some function was not minification safe.

**Comment by CanKattwinkel** [comment]
@kesdeband version 0.9.1 has been released via bower fixing your issue. Thanks for reporting the bug!

@pburgmer can you do the npm release since I probably lack the required access rights?
