### ISSUE TITLE
Unable to setup Demo Hierarchy Examples

### ISSUE THREAD

**Issue by agarg94** [w11k/w11k-select#38]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[* ] question about how to use this project

* **Summary**
Thanks for the work. I was able to get the regular multi-select to work, but am having difficulty setting by the demo hierarchy feature. Could you share a plunker/jsFiddle of a simple use case please?

Thanks.

**Comment by CanKattwinkel** [comment]
Hello @agarg94,

you can take a look at the [demo page](http://w11k.github.io/w11k-select/). 

**src:**
[Controller](https://github.com/w11k/w11k-select/blob/master/demo/src/app/app.controller.ts) + [Template](https://github.com/w11k/w11k-select/blob/master/demo/src/index.html)

If this doesn't solve your issue please transmit the occurring error messages.

**Comment by agarg94** [comment]
Thanks for the prompt response.

Here is the plunker. It has two of the multi-selects. The first normal list is working fine. The second hierarchy does not display the data correctly. We are not getting specific errors but it does not display correctly.

https://plnkr.co/edit/MGOJIkq6sdcR0vGG9KKr?p=preview

Let me know the fix. Thanks

**Comment by CanKattwinkel** [comment]
There are multiple issues with the provided plunker. First of all you are using an outdated AngularJS Version. Hierarchically select is only available from w11k-select^0.10.0. Which requires `"angular": ">= 1.3.0 < 1.7.0"`.

Secondly there was a [breaking change](https://github.com/w11k/w11k-select/blob/master/CHANGELOG.md#breaking-changes) regarding the templates. You are now required to handle the asset loading yourself.  Also bindonce is no longer required as a dependency. 


Here is your working Plunker:
https://plnkr.co/edit/RCVb5Cc6IBTyQeRXltWW

**Comment by agarg94** [comment]
Hi,

We are also having trouble pre-selecting certain options. Could you help us apply with that?

Pre-binding values to the selection, somehow gets over-written. Not sure what we are missing.

Best,
Aditya Garg
