### ISSUE TITLE
Unable to Pre-select

### ISSUE THREAD

**Issue by agarg94** [w11k/w11k-select#39]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[*] question about how to use this project

* **Summary**

Hi,

We are unable to preselect in the demo hierarchy as well. Whenever we set the ids that we wish to select, it resets it as undefined. Here is the plunker you shared before.

https://plnkr.co/edit/RCVb5Cc6IBTyQeRXltWW

Could you please help again?
Appreciate the help.
Thanks.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by agarg94** [comment]
Any updates?

**Comment by pburgmer** [comment]
@CanKattwinkel 
Please take a look at this.

**Comment by CanKattwinkel** [comment]
There is indeed a bug on pre-selecting an hierarchically structure. We'll fix it shortly.

**Comment by agarg94** [comment]
Hi @CanKattwinkel,

Any updates on the timeline? I was hoping to use the library for a project.

Any kind of timeline would help.

Thanks

**Comment by CanKattwinkel** [comment]
@agarg94 currently the fix is scheduled for Tuesday.

**Comment by CanKattwinkel** [comment]
@agarg94 fixed in 0.10.4. 

Thanks for reporting the bug!
