### ISSUE TITLE
Unexpected disabled behavior

### ISSUE THREAD

**Issue by LykPapa** [w11k/w11k-select#8]
I have something like this:

<pre>
div 
   w11k-select
   w11k-select-options="ch.channelName for ch in scope.channels"
   w11k-select-config="{ disabled: scope.channels.length === 1 }"
   ng-model="scope.mutlChSelected"
   ng-change="scope.channelsSelected()" >
/div
</pre>

I print the model var in the only place I change it and I see that it indeed changes.
Then I print it again in the channelsSelected() and it is empty [ ]

The w11k-select box gets disabled but it seems to change my model  too.

Strange thing is that if I change the condition to something like 1 === 1  it will be fine.

Cheers!

**Comment by rebolloso** [comment]
Example: http://plnkr.co/edit/bEDQ5iR6m3tCyhrPAlWB?p=preview

Remove the 'w11k-select-config="select.config"' attribute and the default values load but when the attribute is set it will not load the default values set on ngModel on method creatOptions - $scope.select.selection = [1,2];

**Comment by pburgmer** [comment]
Hi @rebolloso ,

This bug was fixed with release 0.4.7 and later versions. Please update.
I forked your example, updated w11k-select to 0.4.7 and it works.
http://plnkr.co/edit/Gci3jFYNV6gMYSR1sRWN?p=preview

**Comment by pburgmer** [comment]
Hi @LykPapa ,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
